# Google App Engine Configuration
runtime: nodejs18
service: default

# Instance Class (F1 is free tier eligible, F2 is recommended for prod)
instance_class: F2

# Automatic Scaling
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

# Environment Variables
env_variables:
  NODE_ENV: 'production'
  PORT: '8080'
  # Update these with your real database credentials using `gcloud secrets` is better, but this is the start
  # DATABASE_URL: "postgres://user:pass@host:5432/db" 
  # JWT_SECRET: "your-secret"
