-- ============================================================
-- Migration 062: Operational Efficiency Features
-- Phase 2, Month 6 - Auto-scheduling, Travel Optimization,
-- Performance Dashboards, Client Satisfaction
-- ============================================================

-- ============================================================
-- AUTO-SCHEDULING RECOMMENDATIONS
-- ============================================================

-- Schedule recommendations generated by the system
CREATE TABLE IF NOT EXISTS schedule_recommendations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id UUID NOT NULL REFERENCES organizations(id),
  recommendation_type VARCHAR(50) NOT NULL, -- 'fill_gap', 'rebalance', 'optimize_travel', 'skill_match'
  priority VARCHAR(20) DEFAULT 'normal', -- 'low', 'normal', 'high', 'urgent'
  status VARCHAR(20) DEFAULT 'pending', -- 'pending', 'accepted', 'rejected', 'expired'

  -- The recommendation details
  title VARCHAR(255) NOT NULL,
  description TEXT,
  reasoning TEXT, -- Why this recommendation was made

  -- What shifts/visits are affected
  affected_shifts JSONB DEFAULT '[]', -- Array of shift IDs
  affected_caregivers JSONB DEFAULT '[]', -- Array of caregiver IDs
  affected_clients JSONB DEFAULT '[]', -- Array of client IDs

  -- Proposed changes
  proposed_changes JSONB NOT NULL, -- Array of {action, shiftId, caregiverId, etc.}

  -- Metrics
  estimated_savings_minutes INTEGER, -- Travel time saved
  estimated_cost_savings DECIMAL(10,2), -- Dollar savings
  confidence_score DECIMAL(3,2), -- 0.00 to 1.00

  -- Resolution
  reviewed_by UUID REFERENCES users(id),
  reviewed_at TIMESTAMPTZ,
  rejection_reason TEXT,

  -- Tracking
  expires_at TIMESTAMPTZ, -- When recommendation becomes stale
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_schedule_recommendations_org_status
ON schedule_recommendations(organization_id, status);

CREATE INDEX idx_schedule_recommendations_type
ON schedule_recommendations(recommendation_type);

-- ============================================================
-- TRAVEL TIME OPTIMIZATION
-- ============================================================

-- Client locations for travel calculation
CREATE TABLE IF NOT EXISTS client_locations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id UUID NOT NULL REFERENCES clients(id),
  address_type VARCHAR(20) DEFAULT 'primary', -- 'primary', 'secondary', 'temporary'

  -- Full address
  street_address VARCHAR(255),
  apartment VARCHAR(50),
  city VARCHAR(100),
  state VARCHAR(2) DEFAULT 'OH',
  zip_code VARCHAR(10),

  -- Geocoded coordinates for distance calculations
  latitude DECIMAL(10, 8),
  longitude DECIMAL(11, 8),
  geocode_accuracy VARCHAR(20), -- 'rooftop', 'range_interpolated', 'geometric_center'
  geocoded_at TIMESTAMPTZ,

  -- Access notes
  access_instructions TEXT,
  parking_notes TEXT,
  gate_code VARCHAR(20),

  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_client_locations_client ON client_locations(client_id);
CREATE INDEX idx_client_locations_geo ON client_locations(latitude, longitude)
WHERE latitude IS NOT NULL;

-- Caregiver home locations
CREATE TABLE IF NOT EXISTS caregiver_locations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  caregiver_id UUID NOT NULL REFERENCES caregivers(id),

  -- Home address for commute calculations
  street_address VARCHAR(255),
  city VARCHAR(100),
  state VARCHAR(2) DEFAULT 'OH',
  zip_code VARCHAR(10),

  -- Geocoded coordinates
  latitude DECIMAL(10, 8),
  longitude DECIMAL(11, 8),
  geocoded_at TIMESTAMPTZ,

  -- Travel preferences
  max_travel_distance_miles INTEGER DEFAULT 25,
  preferred_areas JSONB DEFAULT '[]', -- Array of zip codes or neighborhoods
  has_reliable_transportation BOOLEAN DEFAULT TRUE,
  transportation_type VARCHAR(20) DEFAULT 'car', -- 'car', 'public_transit', 'ride_share'

  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),

  UNIQUE(caregiver_id)
);

CREATE INDEX idx_caregiver_locations_geo ON caregiver_locations(latitude, longitude)
WHERE latitude IS NOT NULL;

-- Cached travel times between locations
CREATE TABLE IF NOT EXISTS travel_time_cache (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  from_location_type VARCHAR(20) NOT NULL, -- 'caregiver_home', 'client'
  from_location_id UUID NOT NULL,
  to_location_type VARCHAR(20) NOT NULL,
  to_location_id UUID NOT NULL,

  -- Travel metrics
  travel_time_minutes INTEGER NOT NULL,
  distance_miles DECIMAL(6,2),
  route_type VARCHAR(20) DEFAULT 'driving', -- 'driving', 'transit', 'walking'

  -- Time-based variations (rush hour, etc.)
  morning_rush_minutes INTEGER, -- 7-9 AM
  evening_rush_minutes INTEGER, -- 4-7 PM
  off_peak_minutes INTEGER, -- Other times

  -- Cache management
  calculated_at TIMESTAMPTZ DEFAULT NOW(),
  expires_at TIMESTAMPTZ DEFAULT NOW() + INTERVAL '30 days',

  UNIQUE(from_location_type, from_location_id, to_location_type, to_location_id)
);

CREATE INDEX idx_travel_cache_from ON travel_time_cache(from_location_type, from_location_id);
CREATE INDEX idx_travel_cache_expiry ON travel_time_cache(expires_at);

-- ============================================================
-- CAREGIVER PERFORMANCE METRICS
-- ============================================================

-- Daily performance snapshots for each caregiver
CREATE TABLE IF NOT EXISTS caregiver_performance_daily (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  caregiver_id UUID NOT NULL REFERENCES caregivers(id),
  organization_id UUID NOT NULL REFERENCES organizations(id),
  performance_date DATE NOT NULL,

  -- Attendance metrics
  scheduled_shifts INTEGER DEFAULT 0,
  completed_shifts INTEGER DEFAULT 0,
  missed_shifts INTEGER DEFAULT 0,
  late_arrivals INTEGER DEFAULT 0,
  early_departures INTEGER DEFAULT 0,

  -- Time metrics
  scheduled_hours DECIMAL(6,2) DEFAULT 0,
  worked_hours DECIMAL(6,2) DEFAULT 0,
  overtime_hours DECIMAL(6,2) DEFAULT 0,

  -- EVV compliance
  evv_clock_ins INTEGER DEFAULT 0,
  evv_clock_outs INTEGER DEFAULT 0,
  evv_manual_entries INTEGER DEFAULT 0,
  evv_exceptions INTEGER DEFAULT 0,
  evv_compliance_rate DECIMAL(5,2),

  -- Travel efficiency
  total_travel_miles DECIMAL(6,2),
  total_travel_minutes INTEGER,
  visits_per_route INTEGER,

  -- Quality metrics
  client_complaints INTEGER DEFAULT 0,
  client_compliments INTEGER DEFAULT 0,
  documentation_score DECIMAL(5,2), -- 0-100

  created_at TIMESTAMPTZ DEFAULT NOW(),

  UNIQUE(caregiver_id, performance_date)
);

CREATE INDEX idx_caregiver_perf_daily_caregiver
ON caregiver_performance_daily(caregiver_id, performance_date DESC);

CREATE INDEX idx_caregiver_perf_daily_org
ON caregiver_performance_daily(organization_id, performance_date DESC);

-- Monthly aggregated performance
CREATE TABLE IF NOT EXISTS caregiver_performance_monthly (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  caregiver_id UUID NOT NULL REFERENCES caregivers(id),
  organization_id UUID NOT NULL REFERENCES organizations(id),
  performance_month DATE NOT NULL, -- First day of month

  -- Attendance summary
  total_scheduled_shifts INTEGER DEFAULT 0,
  total_completed_shifts INTEGER DEFAULT 0,
  attendance_rate DECIMAL(5,2),
  on_time_rate DECIMAL(5,2),

  -- Hours summary
  total_scheduled_hours DECIMAL(8,2) DEFAULT 0,
  total_worked_hours DECIMAL(8,2) DEFAULT 0,
  total_overtime_hours DECIMAL(8,2) DEFAULT 0,

  -- EVV summary
  evv_compliance_rate DECIMAL(5,2),

  -- Quality summary
  total_complaints INTEGER DEFAULT 0,
  total_compliments INTEGER DEFAULT 0,
  avg_documentation_score DECIMAL(5,2),

  -- Overall score (weighted composite)
  performance_score DECIMAL(5,2), -- 0-100
  performance_tier VARCHAR(10), -- 'gold', 'silver', 'bronze', 'needs_improvement'

  -- Trends
  score_change_from_last_month DECIMAL(5,2),

  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),

  UNIQUE(caregiver_id, performance_month)
);

CREATE INDEX idx_caregiver_perf_monthly_org
ON caregiver_performance_monthly(organization_id, performance_month DESC);

-- ============================================================
-- CLIENT SATISFACTION TRACKING
-- ============================================================

-- Survey templates
CREATE TABLE IF NOT EXISTS satisfaction_survey_templates (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id UUID NOT NULL REFERENCES organizations(id),
  name VARCHAR(100) NOT NULL,
  description TEXT,
  survey_type VARCHAR(50) NOT NULL, -- 'client', 'family', 'caregiver', 'post_visit'

  -- Survey configuration
  questions JSONB NOT NULL, -- Array of {id, text, type, options, required}
  is_active BOOLEAN DEFAULT TRUE,

  -- Scheduling
  auto_send BOOLEAN DEFAULT FALSE,
  send_frequency VARCHAR(20), -- 'after_visit', 'weekly', 'monthly', 'quarterly'

  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_survey_templates_org ON satisfaction_survey_templates(organization_id);

-- Survey responses
CREATE TABLE IF NOT EXISTS satisfaction_survey_responses (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id UUID NOT NULL REFERENCES organizations(id),
  template_id UUID NOT NULL REFERENCES satisfaction_survey_templates(id),

  -- Who is responding
  respondent_type VARCHAR(20) NOT NULL, -- 'client', 'family_member', 'caregiver'
  respondent_id UUID, -- Can be client_id, family contact, or caregiver_id
  respondent_name VARCHAR(100),
  respondent_email VARCHAR(255),
  respondent_phone VARCHAR(20),

  -- What they're responding about
  client_id UUID REFERENCES clients(id),
  caregiver_id UUID REFERENCES caregivers(id),
  visit_id UUID, -- Optional, if post-visit survey

  -- Response data
  responses JSONB NOT NULL, -- {questionId: answer}
  overall_rating INTEGER CHECK (overall_rating BETWEEN 1 AND 5),
  comments TEXT,

  -- Calculated scores
  satisfaction_score DECIMAL(5,2), -- 0-100
  nps_score INTEGER CHECK (nps_score BETWEEN 0 AND 10), -- Net Promoter Score

  -- Follow-up
  requires_follow_up BOOLEAN DEFAULT FALSE,
  follow_up_reason TEXT,
  followed_up_by UUID REFERENCES users(id),
  followed_up_at TIMESTAMPTZ,
  follow_up_notes TEXT,

  -- Status
  status VARCHAR(20) DEFAULT 'completed', -- 'pending', 'completed', 'follow_up_needed', 'resolved'

  submitted_at TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_survey_responses_org ON satisfaction_survey_responses(organization_id);
CREATE INDEX idx_survey_responses_client ON satisfaction_survey_responses(client_id);
CREATE INDEX idx_survey_responses_caregiver ON satisfaction_survey_responses(caregiver_id);
CREATE INDEX idx_survey_responses_status ON satisfaction_survey_responses(status)
WHERE status IN ('pending', 'follow_up_needed');

-- Client satisfaction scores (aggregated)
CREATE TABLE IF NOT EXISTS client_satisfaction_scores (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id UUID NOT NULL REFERENCES clients(id),
  organization_id UUID NOT NULL REFERENCES organizations(id),
  score_period DATE NOT NULL, -- First day of period (month)

  -- Aggregated scores
  avg_satisfaction_score DECIMAL(5,2),
  avg_nps_score DECIMAL(4,2),
  response_count INTEGER DEFAULT 0,

  -- Breakdown
  excellent_count INTEGER DEFAULT 0, -- 5 stars
  good_count INTEGER DEFAULT 0, -- 4 stars
  neutral_count INTEGER DEFAULT 0, -- 3 stars
  poor_count INTEGER DEFAULT 0, -- 2 stars
  terrible_count INTEGER DEFAULT 0, -- 1 star

  -- Trends
  score_change DECIMAL(5,2),
  trend_direction VARCHAR(10), -- 'improving', 'stable', 'declining'

  -- Flags
  at_risk BOOLEAN DEFAULT FALSE,

  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),

  UNIQUE(client_id, score_period)
);

CREATE INDEX idx_satisfaction_scores_org
ON client_satisfaction_scores(organization_id, score_period DESC);

CREATE INDEX idx_satisfaction_scores_at_risk
ON client_satisfaction_scores(organization_id) WHERE at_risk = TRUE;

-- ============================================================
-- OPERATIONAL ANALYTICS VIEWS
-- ============================================================

-- Scheduling efficiency view
CREATE OR REPLACE VIEW scheduling_efficiency AS
SELECT
  s.organization_id,
  DATE_TRUNC('week', s.start_time) AS week_start,
  COUNT(*) AS total_shifts,
  COUNT(*) FILTER (WHERE s.status = 'completed') AS completed_shifts,
  COUNT(*) FILTER (WHERE s.status = 'missed') AS missed_shifts,
  COUNT(*) FILTER (WHERE s.status = 'cancelled') AS cancelled_shifts,
  ROUND(
    (COUNT(*) FILTER (WHERE s.status = 'completed')::DECIMAL / NULLIF(COUNT(*), 0)) * 100,
    1
  ) AS completion_rate,
  SUM(EXTRACT(EPOCH FROM (s.end_time - s.start_time)) / 3600) AS scheduled_hours,
  COUNT(DISTINCT s.caregiver_id) AS active_caregivers,
  COUNT(DISTINCT s.client_id) AS active_clients
FROM shifts s
WHERE s.start_time >= CURRENT_DATE - INTERVAL '90 days'
GROUP BY s.organization_id, DATE_TRUNC('week', s.start_time);

-- Caregiver utilization view
CREATE OR REPLACE VIEW caregiver_utilization AS
SELECT
  c.id AS caregiver_id,
  c.organization_id,
  c.first_name || ' ' || c.last_name AS caregiver_name,
  COUNT(s.id) FILTER (WHERE s.start_time >= CURRENT_DATE - INTERVAL '7 days') AS shifts_this_week,
  SUM(
    EXTRACT(EPOCH FROM (s.end_time - s.start_time)) / 3600
  ) FILTER (WHERE s.start_time >= CURRENT_DATE - INTERVAL '7 days') AS hours_this_week,
  COUNT(DISTINCT s.client_id) FILTER (WHERE s.start_time >= CURRENT_DATE - INTERVAL '7 days') AS clients_this_week,
  cp.avg_documentation_score AS latest_documentation_score,
  cp.evv_compliance_rate AS latest_evv_compliance
FROM caregivers c
LEFT JOIN shifts s ON s.caregiver_id = c.id
LEFT JOIN caregiver_performance_monthly cp ON cp.caregiver_id = c.id
  AND cp.performance_month = DATE_TRUNC('month', CURRENT_DATE)
WHERE c.status = 'active'
GROUP BY c.id, c.organization_id, c.first_name, c.last_name,
  cp.avg_documentation_score, cp.evv_compliance_rate;

-- Client satisfaction summary view
CREATE OR REPLACE VIEW client_satisfaction_summary AS
SELECT
  c.id AS client_id,
  c.organization_id,
  c.first_name || ' ' || c.last_name AS client_name,
  COALESCE(css.avg_satisfaction_score, 0) AS current_satisfaction,
  COALESCE(css.avg_nps_score, 0) AS current_nps,
  COALESCE(css.response_count, 0) AS survey_responses,
  COALESCE(css.trend_direction, 'unknown') AS trend,
  COALESCE(css.at_risk, FALSE) AS at_risk,
  COUNT(ssr.id) FILTER (WHERE ssr.requires_follow_up AND ssr.status != 'resolved') AS pending_follow_ups
FROM clients c
LEFT JOIN client_satisfaction_scores css ON css.client_id = c.id
  AND css.score_period = DATE_TRUNC('month', CURRENT_DATE)
LEFT JOIN satisfaction_survey_responses ssr ON ssr.client_id = c.id
WHERE c.status = 'active'
GROUP BY c.id, c.organization_id, c.first_name, c.last_name,
  css.avg_satisfaction_score, css.avg_nps_score, css.response_count,
  css.trend_direction, css.at_risk;

-- ============================================================
-- FUNCTIONS
-- ============================================================

-- Function to calculate caregiver performance score
CREATE OR REPLACE FUNCTION calculate_caregiver_performance_score(
  p_attendance_rate DECIMAL,
  p_on_time_rate DECIMAL,
  p_evv_compliance_rate DECIMAL,
  p_documentation_score DECIMAL,
  p_complaints INTEGER,
  p_compliments INTEGER
) RETURNS DECIMAL AS $$
DECLARE
  v_score DECIMAL;
BEGIN
  -- Weighted scoring
  -- Attendance: 25%
  -- On-time: 20%
  -- EVV Compliance: 25%
  -- Documentation: 15%
  -- Client feedback: 15%

  v_score :=
    (COALESCE(p_attendance_rate, 0) * 0.25) +
    (COALESCE(p_on_time_rate, 0) * 0.20) +
    (COALESCE(p_evv_compliance_rate, 0) * 0.25) +
    (COALESCE(p_documentation_score, 0) * 0.15) +
    (GREATEST(0, 100 - (COALESCE(p_complaints, 0) * 10) + (COALESCE(p_compliments, 0) * 5)) * 0.15);

  RETURN LEAST(100, GREATEST(0, v_score));
END;
$$ LANGUAGE plpgsql;

-- Function to determine performance tier
CREATE OR REPLACE FUNCTION get_performance_tier(p_score DECIMAL)
RETURNS VARCHAR AS $$
BEGIN
  IF p_score >= 90 THEN RETURN 'gold';
  ELSIF p_score >= 75 THEN RETURN 'silver';
  ELSIF p_score >= 60 THEN RETURN 'bronze';
  ELSE RETURN 'needs_improvement';
  END IF;
END;
$$ LANGUAGE plpgsql;

-- Function to calculate travel distance (Haversine formula)
CREATE OR REPLACE FUNCTION calculate_distance_miles(
  lat1 DECIMAL, lon1 DECIMAL,
  lat2 DECIMAL, lon2 DECIMAL
) RETURNS DECIMAL AS $$
DECLARE
  R DECIMAL := 3959; -- Earth radius in miles
  dLat DECIMAL;
  dLon DECIMAL;
  a DECIMAL;
  c DECIMAL;
BEGIN
  IF lat1 IS NULL OR lon1 IS NULL OR lat2 IS NULL OR lon2 IS NULL THEN
    RETURN NULL;
  END IF;

  dLat := RADIANS(lat2 - lat1);
  dLon := RADIANS(lon2 - lon1);

  a := SIN(dLat/2) * SIN(dLat/2) +
       COS(RADIANS(lat1)) * COS(RADIANS(lat2)) *
       SIN(dLon/2) * SIN(dLon/2);

  c := 2 * ATAN2(SQRT(a), SQRT(1-a));

  RETURN ROUND(R * c, 2);
END;
$$ LANGUAGE plpgsql;

-- Insert default survey template
INSERT INTO satisfaction_survey_templates (
  organization_id,
  name,
  description,
  survey_type,
  questions,
  is_active,
  auto_send,
  send_frequency
) SELECT
  o.id,
  'Standard Client Satisfaction Survey',
  'Monthly survey to assess client satisfaction with care services',
  'client',
  '[
    {"id": "q1", "text": "How satisfied are you with the care you receive?", "type": "rating", "required": true},
    {"id": "q2", "text": "How satisfied are you with your caregiver(s)?", "type": "rating", "required": true},
    {"id": "q3", "text": "Is your caregiver punctual and reliable?", "type": "rating", "required": true},
    {"id": "q4", "text": "Does your caregiver treat you with respect and dignity?", "type": "rating", "required": true},
    {"id": "q5", "text": "Does your caregiver complete all assigned tasks?", "type": "rating", "required": true},
    {"id": "q6", "text": "How easy is it to communicate with the care team?", "type": "rating", "required": true},
    {"id": "q7", "text": "How likely are you to recommend our services to others?", "type": "nps", "required": true},
    {"id": "q8", "text": "What could we do to improve your care experience?", "type": "text", "required": false},
    {"id": "q9", "text": "Any other comments or feedback?", "type": "text", "required": false}
  ]'::JSONB,
  TRUE,
  TRUE,
  'monthly'
FROM organizations o
WHERE NOT EXISTS (
  SELECT 1 FROM satisfaction_survey_templates sst
  WHERE sst.organization_id = o.id AND sst.survey_type = 'client'
);

-- ============================================================
-- ROW LEVEL SECURITY
-- ============================================================

ALTER TABLE schedule_recommendations ENABLE ROW LEVEL SECURITY;
ALTER TABLE client_locations ENABLE ROW LEVEL SECURITY;
ALTER TABLE caregiver_locations ENABLE ROW LEVEL SECURITY;
ALTER TABLE travel_time_cache ENABLE ROW LEVEL SECURITY;
ALTER TABLE caregiver_performance_daily ENABLE ROW LEVEL SECURITY;
ALTER TABLE caregiver_performance_monthly ENABLE ROW LEVEL SECURITY;
ALTER TABLE satisfaction_survey_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE satisfaction_survey_responses ENABLE ROW LEVEL SECURITY;
ALTER TABLE client_satisfaction_scores ENABLE ROW LEVEL SECURITY;

-- RLS policies for organization-scoped access
CREATE POLICY schedule_recommendations_org_policy ON schedule_recommendations
  FOR ALL USING (organization_id = current_setting('app.organization_id')::UUID);

CREATE POLICY caregiver_performance_daily_org_policy ON caregiver_performance_daily
  FOR ALL USING (organization_id = current_setting('app.organization_id')::UUID);

CREATE POLICY caregiver_performance_monthly_org_policy ON caregiver_performance_monthly
  FOR ALL USING (organization_id = current_setting('app.organization_id')::UUID);

CREATE POLICY survey_templates_org_policy ON satisfaction_survey_templates
  FOR ALL USING (organization_id = current_setting('app.organization_id')::UUID);

CREATE POLICY survey_responses_org_policy ON satisfaction_survey_responses
  FOR ALL USING (organization_id = current_setting('app.organization_id')::UUID);

CREATE POLICY satisfaction_scores_org_policy ON client_satisfaction_scores
  FOR ALL USING (organization_id = current_setting('app.organization_id')::UUID);

COMMENT ON TABLE schedule_recommendations IS 'AI-generated scheduling recommendations for optimization';
COMMENT ON TABLE client_locations IS 'Client address and location data for travel calculations';
COMMENT ON TABLE caregiver_locations IS 'Caregiver home locations and travel preferences';
COMMENT ON TABLE travel_time_cache IS 'Cached travel times between locations';
COMMENT ON TABLE caregiver_performance_daily IS 'Daily performance metrics for caregivers';
COMMENT ON TABLE caregiver_performance_monthly IS 'Monthly aggregated caregiver performance';
COMMENT ON TABLE satisfaction_survey_templates IS 'Survey templates for satisfaction tracking';
COMMENT ON TABLE satisfaction_survey_responses IS 'Individual survey responses';
COMMENT ON TABLE client_satisfaction_scores IS 'Aggregated client satisfaction scores';
