import { lazy, ComponentType } from 'react';

export interface FormDefinition {
  id: string;
  slug: string;
  title: string;
  description: string;
  category: 'incident' | 'employee' | 'client' | 'compliance' | 'sfc' | 'service';
  hasSignature: boolean;
  isLogTable: boolean;
  policyReference?: string;
  regulatoryRef?: string;
  originalFile: string;
  component: React.LazyExoticComponent<ComponentType>;
}

export const FORM_REGISTRY: FormDefinition[] = [
  {
    id: '01',
    slug: 'incident-report',
    title: 'Incident Report Form',
    description: 'Report critical incidents, reportable incidents, or unusual occurrences',
    category: 'incident',
    hasSignature: true,
    isLogTable: false,
    policyReference: 'Policy 18',
    originalFile: '01_Incident_Report_Form.xlsx',
    component: lazy(() => import('./IncidentReportForm')),
  },
  {
    id: '02',
    slug: 'incident-log',
    title: 'Incident Log',
    description: 'Summary log of all incidents for quarterly QAPI review',
    category: 'incident',
    hasSignature: false,
    isLogTable: true,
    policyReference: 'Policy 18',
    originalFile: '02_Incident_Log.xlsx',
    component: lazy(() => import('./IncidentLog')),
  },
  {
    id: '03',
    slug: 'supervisory-visit',
    title: 'Supervisory Visit Form',
    description: 'Document supervisory visits to caregivers (required every 60 days)',
    category: 'client',
    hasSignature: true,
    isLogTable: false,
    policyReference: 'Policy 44',
    regulatoryRef: 'OAC 173-39-02.11(C)(4)',
    originalFile: '03_Supervisory_Visit_Form.xlsx',
    component: lazy(() => import('./SupervisoryVisitForm')),
  },
  {
    id: '04',
    slug: 'initial-assessment',
    title: 'Initial Assessment Form',
    description: 'Comprehensive initial assessment of new client (within 5 days of referral)',
    category: 'client',
    hasSignature: true,
    isLogTable: false,
    policyReference: 'Policy 41',
    originalFile: '04_Initial_Assessment_Form.xlsx',
    component: lazy(() => import('./InitialAssessmentForm')),
  },
  {
    id: '05',
    slug: 'task-time-sheet',
    title: 'Task / Time Sheet',
    description: 'Service verification — document all tasks performed and time spent per visit',
    category: 'service',
    hasSignature: false,
    isLogTable: false,
    policyReference: 'Policy 9',
    originalFile: '05_Task_Time_Sheet.xlsx',
    component: lazy(() => import('./TaskTimeSheet')),
  },
  {
    id: '06',
    slug: 'release-of-information',
    title: 'Release of Information Form',
    description: 'HIPAA-compliant authorization for release of client health information',
    category: 'client',
    hasSignature: true,
    isLogTable: false,
    policyReference: 'Policy 6',
    originalFile: '06_Release_of_Information_Form.xlsx',
    component: lazy(() => import('./ReleaseOfInformationForm')),
  },
  {
    id: '07',
    slug: 'orientation-checklist',
    title: 'Orientation Checklist',
    description: 'Document completion of new employee orientation (16 required topics)',
    category: 'employee',
    hasSignature: true,
    isLogTable: false,
    policyReference: 'Policy 28',
    regulatoryRef: 'OAC 173-39-02.11(C)(3)(c)',
    originalFile: '07_Orientation_Checklist.xlsx',
    component: lazy(() => import('./OrientationChecklist')),
  },
  {
    id: '08',
    slug: 'code-of-ethics',
    title: 'Code of Ethics Acknowledgment',
    description: 'Acknowledge receipt and agreement to comply with Code of Ethics',
    category: 'employee',
    hasSignature: true,
    isLogTable: false,
    policyReference: 'Policy 40',
    originalFile: '08_Code_of_Ethics_Acknowledgment.xlsx',
    component: lazy(() => import('./CodeOfEthicsAck')),
  },
  {
    id: '09',
    slug: 'handbook-acknowledgment',
    title: 'Employee Handbook Acknowledgment',
    description: 'Acknowledge receipt and understanding of Employee Handbook',
    category: 'employee',
    hasSignature: true,
    isLogTable: false,
    policyReference: 'Policy 28',
    originalFile: '09_Employee_Handbook_Acknowledgment.xlsx',
    component: lazy(() => import('./HandbookAck')),
  },
  {
    id: '10',
    slug: 'random-checks-log',
    title: 'Random Checks Log',
    description: 'Log of unannounced random checks of caregiver performance and client safety',
    category: 'compliance',
    hasSignature: false,
    isLogTable: true,
    policyReference: 'Policy 22',
    originalFile: '10_Random_Checks_Log.xlsx',
    component: lazy(() => import('./RandomChecksLog')),
  },
  {
    id: '11',
    slug: 'case-manager-notification',
    title: 'Case Manager Notification Log',
    description: 'Track all notifications made to Case Managers regarding clients',
    category: 'compliance',
    hasSignature: false,
    isLogTable: true,
    policyReference: 'Policy 19',
    originalFile: '11_Case_Manager_Notification_Log.xlsx',
    component: lazy(() => import('./CaseManagerNotificationLog')),
  },
  {
    id: '12',
    slug: 'disclosure-of-ownership',
    title: 'Disclosure of Ownership',
    description: 'Disclose all persons with ownership or controlling interest in agency',
    category: 'compliance',
    hasSignature: true,
    isLogTable: false,
    policyReference: 'Policy 12',
    originalFile: '12_Disclosure_of_Ownership.xlsx',
    component: lazy(() => import('./DisclosureOfOwnership')),
  },
  {
    id: '13',
    slug: 'volunteer-orientation',
    title: 'Volunteer Orientation Checklist',
    description: 'Document orientation of volunteers (6 required topics)',
    category: 'employee',
    hasSignature: true,
    isLogTable: false,
    policyReference: 'Policy 59',
    originalFile: '13_Volunteer_Orientation_Checklist.xlsx',
    component: lazy(() => import('./VolunteerOrientationChecklist')),
  },
  {
    id: '14',
    slug: 'sfc-individual-choice',
    title: 'SFC Individual Choice Form',
    description: "Document individual's choice of family caregiver for SFC services",
    category: 'sfc',
    hasSignature: true,
    isLogTable: false,
    policyReference: 'Policy 60',
    originalFile: '14_SFC_Individual_Choice_Form.xlsx',
    component: lazy(() => import('./SFCIndividualChoiceForm')),
  },
  {
    id: '15',
    slug: 'sfc-coaching-visit',
    title: 'SFC Coaching Visit Form',
    description: 'Document coaching and support visits to SFC caregivers (every 60 days)',
    category: 'sfc',
    hasSignature: true,
    isLogTable: false,
    policyReference: 'Policy 60',
    originalFile: '15_SFC_Coaching_Visit_Form.xlsx',
    component: lazy(() => import('./SFCCoachingVisitForm')),
  },
  {
    id: '16',
    slug: 'record-destruction-log',
    title: 'Record Destruction Log',
    description: 'Document destruction of client and personnel records per retention policies',
    category: 'compliance',
    hasSignature: false,
    isLogTable: true,
    policyReference: 'Policy 24',
    originalFile: '16_Record_Destruction_Log.xlsx',
    component: lazy(() => import('./RecordDestructionLog')),
  },
  {
    id: '17',
    slug: 'employee-list',
    title: 'Employee List',
    description: 'Complete list of employees, positions, hire dates, and credentials',
    category: 'employee',
    hasSignature: false,
    isLogTable: true,
    originalFile: '17_Employee_List.xlsx',
    component: lazy(() => import('./EmployeeListReport')),
  },
  {
    id: '18',
    slug: 'pca-written-competency',
    title: 'PCA Written Competency Assessment',
    description: 'Document PCA written competency test results (minimum 80% passing)',
    category: 'employee',
    hasSignature: true,
    isLogTable: false,
    policyReference: 'Policy 14',
    originalFile: '18_PCA_Written_Competency_Assessment.xlsx',
    component: lazy(() => import('./PCAWrittenCompetency')),
  },
  {
    id: '19',
    slug: 'pca-skills-demonstration',
    title: 'PCA Skills Return Demonstration',
    description: 'Document PCA skills competency via return demonstration (observed by RN)',
    category: 'employee',
    hasSignature: true,
    isLogTable: false,
    policyReference: 'Policy 14',
    originalFile: '19_PCA_Skills_Return_Demonstration.xlsx',
    component: lazy(() => import('./PCASkillsDemonstration')),
  },
  {
    id: '20',
    slug: 'bcii-log',
    title: 'BCI/FBI Background Check Log',
    description: 'Track criminal background checks for all employees (5-year rechecks)',
    category: 'compliance',
    hasSignature: false,
    isLogTable: true,
    originalFile: '20_BCII_Log_Serenity.xlsx',
    component: lazy(() => import('./BCIILog')),
  },
];

export function getFormBySlug(slug: string): FormDefinition | undefined {
  return FORM_REGISTRY.find(f => f.slug === slug);
}

export function getFormsByCategory(category: FormDefinition['category']): FormDefinition[] {
  return FORM_REGISTRY.filter(f => f.category === category);
}

export const CATEGORY_LABELS: Record<FormDefinition['category'], string> = {
  incident: 'Incident Management',
  employee: 'Employee / HR',
  client: 'Client / Patient',
  compliance: 'Compliance & Records',
  sfc: 'Structured Family Caregiving',
  service: 'Service Delivery',
};

export const CATEGORY_COLORS: Record<FormDefinition['category'], string> = {
  incident: 'bg-red-100 text-red-800',
  employee: 'bg-blue-100 text-blue-800',
  client: 'bg-green-100 text-green-800',
  compliance: 'bg-purple-100 text-purple-800',
  sfc: 'bg-amber-100 text-amber-800',
  service: 'bg-teal-100 text-teal-800',
};
